  version: "3.9"
  services:

  rabbitmq:
      image: rabbitmq:3-management
      ports:
        - "5672:5672"     # AMQP (backend)
        - "15672:15672"   # Management UI
      networks:
        - artchain-network

    api-gateway:
      build:
        context: ./api-gateway
      ports:
        - "3000:3000"
      env_file:
        - ./api-gateway/.env
      depends_on:
        - user-service
        - art-service
        - notification-service
      networks:
        - artchain-network

    user-service:
      build:
        context: ./services/user-service
      ports:
        - "3001:3001"
      env_file:
        - ./services/user-service/.env
      networks:
        - artchain-network

    wallet-service:
      build:
        context: ./services/wallet-service
      ports:
        - "3002:3002"
      env_file:
        - ./services/wallet-service/.env
      networks:
        - artchain-network    

    art-service:
      build:
        context: ./services/art-service
      ports:
        - "3003:3003"
      env_file:
        - ./services/art-service/.env
      networks:
        - artchain-network

    search-service:
      build:
        context: ./services/search-service
      ports:
        - "3004:3004"
      env_file:
        - ./services/search-service/.env
      networks:
        - artchain-network

    notification-service:
      build:
        context: ./services/notification-service
      ports:
        - "3005:3005"
      env_file:
        - ./services/notification-service/.env
      networks:
        - artchain-network

    chat-service:
      build:
        context: ./services/chat-service
      ports:
        - "3006:3006"
      env_file:
        - ./services/chat-service/.env
      networks:
        - artchain-network

    call-service:
      build:
        context: ./services/call-service
      ports:
        - "3007:3007"
      env_file:
        - ./services/call-service/.env
      networks:
        - artchain-network

  networks:
    artchain-network:
      driver: bridge
